const { selInputEmail, selButtonLogin, selInputPassword } = require("./Login");
const { selLinkNewPost, selLinkTags, selLinkPosts } = require("./Dashboard");

const {
  selButtonBack,
  selDivPublish,
  selDivUpdate,
  selButtonUpdate,
  selTextAreaTitle,
  selButtonPublish,
  selButtonSchedule,
  selButtonDeletePost,
  selSpanSettingsMenu,
  selButtonPostSettings,
  selRadioButtonSchedule,
  selButtonConfirmDeletePost,
  selButtonPublishConfirmation,
  selButtonScheduleConfirmation,
  selInputTag,
  selFirstTagOption,
} = require("./PostEditor");

const {
  selAllOption,
  selDraftOption,
  selPublishedOption,
  selScheduledOption,
  selFilterByStatus,
  selListPostItem,
  selOlPostList,
  selPostItemTitle,
  selPostItemTag,
} = require("./PostsList");

const {
  selInputName,
  selTextAreaDesc,
  selButtonSave,
  selButtonDeleteTag,
  selButtonConfirmDeleteTag,
} = require("./TagsEditor");

const {
  selListTagItem,
  selLinkNewTag,
  selOlTagList,
  selTagItemTitle,
  selTagItemName,
} = require("./TagsList");

const {
  selCreatePage,
  selPageButton,
  selTitlePage,
  selNewPageOutsideArea,
  selPublishDropdown,
  selPublishButton,
  selPagesBackButton,
  selPagesList,
  selPageTitle,
  selSortDropdown,
  selViewSiteButton,
  selTagDropdown,
  selTag,
  selPageTag,
  selSortRecentlyUpdated,
  selUpdateDropdown,
  selFeature,
  selFeatureFilter,
  selUnpublishPage,
  selDeletePage,
  selDeleteConfirmation,
  selDarkMode,
  selCanvasHeader,
  selPreview,
  selPreviewContainer,
  selUserProfile,
  selUserEmail,
  selUsername,
} = require("./PageList");

module.exports = {
  selInputEmail,
  selButtonLogin,
  selLinkNewPost,
  selLinkTags,
  selButtonBack,
  selDivPublish,
  selDivUpdate,
  selButtonUpdate,
  selInputPassword,
  selTextAreaTitle,
  selButtonPublish,
  selButtonSchedule,
  selButtonDeletePost,
  selSpanSettingsMenu,
  selButtonPostSettings,
  selRadioButtonSchedule,
  selButtonConfirmDeletePost,
  selButtonPublishConfirmation,
  selButtonScheduleConfirmation,
  selPostItemTitle,
  selAllOption,
  selDraftOption,
  selPublishedOption,
  selScheduledOption,
  selFilterByStatus,
  selListPostItem,
  selOlPostList,
  selInputName,
  selTextAreaDesc,
  selButtonSave,
  selListTagItem,
  selLinkNewTag,
  selOlTagList,
  selTagItemTitle,
  selCreatePage,
  selPageButton,
  selTitlePage,
  selNewPageOutsideArea,
  selPublishDropdown,
  selPublishButton,
  selPagesBackButton,
  selPagesList,
  selPageTitle,
  selSortDropdown,
  selViewSiteButton,
  selTagDropdown,
  selTag,
  selPageTag,
  selSortRecentlyUpdated,
  selUpdateDropdown,
  selTagItemName,
  selButtonDeleteTag,
  selButtonConfirmDeleteTag,
  selLinkPosts,
  selInputTag,
  selFirstTagOption,
  selPostItemTag,
  selFeature,
  selFeatureFilter,
  selUnpublishPage,
  selDeletePage,
  selDeleteConfirmation,
  selDarkMode,
  selCanvasHeader,
  selPreview,
  selPreviewContainer,
  selUserProfile,
  selUserEmail,
  selUsername,
};
